version: "3.3"
services:
  core:
    links:
      - mongo
    depends_on:
      - mongo
    build: .
    restart: always
    ports:
      - 2023:2023
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

